services:
  orchestrator:
    image: mageai/mageai:latest
    container_name: jobs_monitor_orchestrator
    ports:
      - "6789:6789"
      - "8080:8080"
    volumes:
      - .:/home/src
    env_file:
      - .env
    environment:
      USER_CODE_PATH: /home/src/jobs_monitor_mage
      # Set the data path as wee so there isn't a mage_data directory
      MAGE_DATA_PATH: /home/src/jobs_monitor_mage/data
    depends_on:
      - data-controller
  data-controller:
    image: postgres:latest
    container_name: jobs_monitor_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
